// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.31.0
// 	protoc        v4.25.0--rc2
// source: messages.proto

package message

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type Ping struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields
}

func (x *Ping) Reset() {
	*x = Ping{}
	if protoimpl.UnsafeEnabled {
		mi := &file_messages_proto_msgTypes[0]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *Ping) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Ping) ProtoMessage() {}

func (x *Ping) ProtoReflect() protoreflect.Message {
	mi := &file_messages_proto_msgTypes[0]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Ping.ProtoReflect.Descriptor instead.
func (*Ping) Descriptor() ([]byte, []int) {
	return file_messages_proto_rawDescGZIP(), []int{0}
}

// Main event structure
// events are used to transmit actions from either
// server -> client
// client -> server
type Event struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	// Event type
	Type uint32 `protobuf:"varint,1,opt,name=type,proto3" json:"type,omitempty"`
	// Sender id/Target id
	Id uint32 `protobuf:"varint,2,opt,name=id,proto3" json:"id,omitempty"`
	// The event
	E []byte `protobuf:"bytes,3,opt,name=e,proto3" json:"e,omitempty"`
}

func (x *Event) Reset() {
	*x = Event{}
	if protoimpl.UnsafeEnabled {
		mi := &file_messages_proto_msgTypes[1]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *Event) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Event) ProtoMessage() {}

func (x *Event) ProtoReflect() protoreflect.Message {
	mi := &file_messages_proto_msgTypes[1]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Event.ProtoReflect.Descriptor instead.
func (*Event) Descriptor() ([]byte, []int) {
	return file_messages_proto_rawDescGZIP(), []int{1}
}

func (x *Event) GetType() uint32 {
	if x != nil {
		return x.Type
	}
	return 0
}

func (x *Event) GetId() uint32 {
	if x != nil {
		return x.Id
	}
	return 0
}

func (x *Event) GetE() []byte {
	if x != nil {
		return x.E
	}
	return nil
}

// Register
type Register struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Nick string `protobuf:"bytes,1,opt,name=nick,proto3" json:"nick,omitempty"`
}

func (x *Register) Reset() {
	*x = Register{}
	if protoimpl.UnsafeEnabled {
		mi := &file_messages_proto_msgTypes[2]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *Register) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Register) ProtoMessage() {}

func (x *Register) ProtoReflect() protoreflect.Message {
	mi := &file_messages_proto_msgTypes[2]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Register.ProtoReflect.Descriptor instead.
func (*Register) Descriptor() ([]byte, []int) {
	return file_messages_proto_rawDescGZIP(), []int{2}
}

func (x *Register) GetNick() string {
	if x != nil {
		return x.Nick
	}
	return ""
}

type RegisterOk struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Id uint32 `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	// map data should only be sent once at the start
	// as the response to a client register
	//
	//	message MapData {
	//	  message MapRow {
	//	    repeated uint32 asset = 1;
	//	  }
	//	  repeated MapRow y = 1;
	//	}
	//
	// MapData ground = 2;
	// MapData stuff = 3;
	FovX   int32           `protobuf:"varint,4,opt,name=fovX,proto3" json:"fovX,omitempty"`
	FovY   int32           `protobuf:"varint,5,opt,name=fovY,proto3" json:"fovY,omitempty"`
	Self   *PlayerAction   `protobuf:"bytes,6,opt,name=self,proto3" json:"self,omitempty"`
	Spawns []*PlayerAction `protobuf:"bytes,7,rep,name=spawns,proto3" json:"spawns,omitempty"`
	MaxHP  uint32          `protobuf:"varint,8,opt,name=maxHP,proto3" json:"maxHP,omitempty"`
	MaxMP  uint32          `protobuf:"varint,9,opt,name=maxMP,proto3" json:"maxMP,omitempty"`
	HP     uint32          `protobuf:"varint,10,opt,name=HP,proto3" json:"HP,omitempty"`
	MP     uint32          `protobuf:"varint,11,opt,name=MP,proto3" json:"MP,omitempty"`
}

func (x *RegisterOk) Reset() {
	*x = RegisterOk{}
	if protoimpl.UnsafeEnabled {
		mi := &file_messages_proto_msgTypes[3]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *RegisterOk) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RegisterOk) ProtoMessage() {}

func (x *RegisterOk) ProtoReflect() protoreflect.Message {
	mi := &file_messages_proto_msgTypes[3]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RegisterOk.ProtoReflect.Descriptor instead.
func (*RegisterOk) Descriptor() ([]byte, []int) {
	return file_messages_proto_rawDescGZIP(), []int{3}
}

func (x *RegisterOk) GetId() uint32 {
	if x != nil {
		return x.Id
	}
	return 0
}

func (x *RegisterOk) GetFovX() int32 {
	if x != nil {
		return x.FovX
	}
	return 0
}

func (x *RegisterOk) GetFovY() int32 {
	if x != nil {
		return x.FovY
	}
	return 0
}

func (x *RegisterOk) GetSelf() *PlayerAction {
	if x != nil {
		return x.Self
	}
	return nil
}

func (x *RegisterOk) GetSpawns() []*PlayerAction {
	if x != nil {
		return x.Spawns
	}
	return nil
}

func (x *RegisterOk) GetMaxHP() uint32 {
	if x != nil {
		return x.MaxHP
	}
	return 0
}

func (x *RegisterOk) GetMaxMP() uint32 {
	if x != nil {
		return x.MaxMP
	}
	return 0
}

func (x *RegisterOk) GetHP() uint32 {
	if x != nil {
		return x.HP
	}
	return 0
}

func (x *RegisterOk) GetMP() uint32 {
	if x != nil {
		return x.MP
	}
	return 0
}

// Move request
type Move struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Dir uint32 `protobuf:"varint,1,opt,name=dir,proto3" json:"dir,omitempty"`
}

func (x *Move) Reset() {
	*x = Move{}
	if protoimpl.UnsafeEnabled {
		mi := &file_messages_proto_msgTypes[4]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *Move) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Move) ProtoMessage() {}

func (x *Move) ProtoReflect() protoreflect.Message {
	mi := &file_messages_proto_msgTypes[4]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Move.ProtoReflect.Descriptor instead.
func (*Move) Descriptor() ([]byte, []int) {
	return file_messages_proto_rawDescGZIP(), []int{4}
}

func (x *Move) GetDir() uint32 {
	if x != nil {
		return x.Dir
	}
	return 0
}

// Move response
type MoveOk struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Ok bool `protobuf:"varint,1,opt,name=ok,proto3" json:"ok,omitempty"`
}

func (x *MoveOk) Reset() {
	*x = MoveOk{}
	if protoimpl.UnsafeEnabled {
		mi := &file_messages_proto_msgTypes[5]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *MoveOk) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*MoveOk) ProtoMessage() {}

func (x *MoveOk) ProtoReflect() protoreflect.Message {
	mi := &file_messages_proto_msgTypes[5]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use MoveOk.ProtoReflect.Descriptor instead.
func (*MoveOk) Descriptor() ([]byte, []int) {
	return file_messages_proto_rawDescGZIP(), []int{5}
}

func (x *MoveOk) GetOk() bool {
	if x != nil {
		return x.Ok
	}
	return false
}

// Direction change event (clients send this, but is also used to broadcast)
type Dir struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Dir uint32 `protobuf:"varint,1,opt,name=dir,proto3" json:"dir,omitempty"`
}

func (x *Dir) Reset() {
	*x = Dir{}
	if protoimpl.UnsafeEnabled {
		mi := &file_messages_proto_msgTypes[6]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *Dir) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Dir) ProtoMessage() {}

func (x *Dir) ProtoReflect() protoreflect.Message {
	mi := &file_messages_proto_msgTypes[6]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Dir.ProtoReflect.Descriptor instead.
func (*Dir) Descriptor() ([]byte, []int) {
	return file_messages_proto_rawDescGZIP(), []int{6}
}

func (x *Dir) GetDir() uint32 {
	if x != nil {
		return x.Dir
	}
	return 0
}

// Melee request
type CastMelee struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields
}

func (x *CastMelee) Reset() {
	*x = CastMelee{}
	if protoimpl.UnsafeEnabled {
		mi := &file_messages_proto_msgTypes[7]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *CastMelee) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CastMelee) ProtoMessage() {}

func (x *CastMelee) ProtoReflect() protoreflect.Message {
	mi := &file_messages_proto_msgTypes[7]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CastMelee.ProtoReflect.Descriptor instead.
func (*CastMelee) Descriptor() ([]byte, []int) {
	return file_messages_proto_rawDescGZIP(), []int{7}
}

// Melee response
// - ok: did you hit something?
// - id: ok who?
// - dmg: by how much.
type CastMeleeOk struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Ok  bool   `protobuf:"varint,1,opt,name=ok,proto3" json:"ok,omitempty"`
	Id  uint32 `protobuf:"varint,2,opt,name=id,proto3" json:"id,omitempty"` // the id of what we hit
	Dmg uint32 `protobuf:"varint,3,opt,name=dmg,proto3" json:"dmg,omitempty"`
}

func (x *CastMeleeOk) Reset() {
	*x = CastMeleeOk{}
	if protoimpl.UnsafeEnabled {
		mi := &file_messages_proto_msgTypes[8]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *CastMeleeOk) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CastMeleeOk) ProtoMessage() {}

func (x *CastMeleeOk) ProtoReflect() protoreflect.Message {
	mi := &file_messages_proto_msgTypes[8]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CastMeleeOk.ProtoReflect.Descriptor instead.
func (*CastMeleeOk) Descriptor() ([]byte, []int) {
	return file_messages_proto_rawDescGZIP(), []int{8}
}

func (x *CastMeleeOk) GetOk() bool {
	if x != nil {
		return x.Ok
	}
	return false
}

func (x *CastMeleeOk) GetId() uint32 {
	if x != nil {
		return x.Id
	}
	return 0
}

func (x *CastMeleeOk) GetDmg() uint32 {
	if x != nil {
		return x.Dmg
	}
	return 0
}

// Melee event, you got hit!
type RecivedMelee struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Id  uint32 `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	Dmg uint32 `protobuf:"varint,2,opt,name=dmg,proto3" json:"dmg,omitempty"`
	Hp  uint32 `protobuf:"varint,3,opt,name=hp,proto3" json:"hp,omitempty"`
}

func (x *RecivedMelee) Reset() {
	*x = RecivedMelee{}
	if protoimpl.UnsafeEnabled {
		mi := &file_messages_proto_msgTypes[9]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *RecivedMelee) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RecivedMelee) ProtoMessage() {}

func (x *RecivedMelee) ProtoReflect() protoreflect.Message {
	mi := &file_messages_proto_msgTypes[9]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RecivedMelee.ProtoReflect.Descriptor instead.
func (*RecivedMelee) Descriptor() ([]byte, []int) {
	return file_messages_proto_rawDescGZIP(), []int{9}
}

func (x *RecivedMelee) GetId() uint32 {
	if x != nil {
		return x.Id
	}
	return 0
}

func (x *RecivedMelee) GetDmg() uint32 {
	if x != nil {
		return x.Dmg
	}
	return 0
}

func (x *RecivedMelee) GetHp() uint32 {
	if x != nil {
		return x.Hp
	}
	return 0
}

// Melee broadcast event,
// every player reciving this has the ids of the playes involved,
// so we just send this to reproduce the animations in their clients.
type MeleeHit struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Ok   bool   `protobuf:"varint,1,opt,name=ok,proto3" json:"ok,omitempty"`
	From uint32 `protobuf:"varint,2,opt,name=from,proto3" json:"from,omitempty"`
	To   uint32 `protobuf:"varint,3,opt,name=to,proto3" json:"to,omitempty"`
}

func (x *MeleeHit) Reset() {
	*x = MeleeHit{}
	if protoimpl.UnsafeEnabled {
		mi := &file_messages_proto_msgTypes[10]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *MeleeHit) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*MeleeHit) ProtoMessage() {}

func (x *MeleeHit) ProtoReflect() protoreflect.Message {
	mi := &file_messages_proto_msgTypes[10]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use MeleeHit.ProtoReflect.Descriptor instead.
func (*MeleeHit) Descriptor() ([]byte, []int) {
	return file_messages_proto_rawDescGZIP(), []int{10}
}

func (x *MeleeHit) GetOk() bool {
	if x != nil {
		return x.Ok
	}
	return false
}

func (x *MeleeHit) GetFrom() uint32 {
	if x != nil {
		return x.From
	}
	return 0
}

func (x *MeleeHit) GetTo() uint32 {
	if x != nil {
		return x.To
	}
	return 0
}

// Spell request
// - x, y: where in the map you tried to cast
// - spell: what spell spell.Spell
type CastSpell struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	X     uint32 `protobuf:"varint,1,opt,name=x,proto3" json:"x,omitempty"`
	Y     uint32 `protobuf:"varint,2,opt,name=y,proto3" json:"y,omitempty"`
	Spell uint32 `protobuf:"varint,3,opt,name=spell,proto3" json:"spell,omitempty"`
}

func (x *CastSpell) Reset() {
	*x = CastSpell{}
	if protoimpl.UnsafeEnabled {
		mi := &file_messages_proto_msgTypes[11]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *CastSpell) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CastSpell) ProtoMessage() {}

func (x *CastSpell) ProtoReflect() protoreflect.Message {
	mi := &file_messages_proto_msgTypes[11]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CastSpell.ProtoReflect.Descriptor instead.
func (*CastSpell) Descriptor() ([]byte, []int) {
	return file_messages_proto_rawDescGZIP(), []int{11}
}

func (x *CastSpell) GetX() uint32 {
	if x != nil {
		return x.X
	}
	return 0
}

func (x *CastSpell) GetY() uint32 {
	if x != nil {
		return x.Y
	}
	return 0
}

func (x *CastSpell) GetSpell() uint32 {
	if x != nil {
		return x.Spell
	}
	return 0
}

// Spell response
// - ok: did you hit something?
// - id: ok who?
// - dmg: by how much.
type CastSpellOk struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Ok    bool   `protobuf:"varint,1,opt,name=ok,proto3" json:"ok,omitempty"`
	Id    uint32 `protobuf:"varint,2,opt,name=id,proto3" json:"id,omitempty"` // the id of what we hit
	Dmg   uint32 `protobuf:"varint,3,opt,name=dmg,proto3" json:"dmg,omitempty"`
	Spell uint32 `protobuf:"varint,4,opt,name=spell,proto3" json:"spell,omitempty"`
	Mp    uint32 `protobuf:"varint,5,opt,name=mp,proto3" json:"mp,omitempty"`
}

func (x *CastSpellOk) Reset() {
	*x = CastSpellOk{}
	if protoimpl.UnsafeEnabled {
		mi := &file_messages_proto_msgTypes[12]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *CastSpellOk) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CastSpellOk) ProtoMessage() {}

func (x *CastSpellOk) ProtoReflect() protoreflect.Message {
	mi := &file_messages_proto_msgTypes[12]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CastSpellOk.ProtoReflect.Descriptor instead.
func (*CastSpellOk) Descriptor() ([]byte, []int) {
	return file_messages_proto_rawDescGZIP(), []int{12}
}

func (x *CastSpellOk) GetOk() bool {
	if x != nil {
		return x.Ok
	}
	return false
}

func (x *CastSpellOk) GetId() uint32 {
	if x != nil {
		return x.Id
	}
	return 0
}

func (x *CastSpellOk) GetDmg() uint32 {
	if x != nil {
		return x.Dmg
	}
	return 0
}

func (x *CastSpellOk) GetSpell() uint32 {
	if x != nil {
		return x.Spell
	}
	return 0
}

func (x *CastSpellOk) GetMp() uint32 {
	if x != nil {
		return x.Mp
	}
	return 0
}

// Spell event, you got hit!
type RecivedSpell struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Id    uint32 `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	Dmg   uint32 `protobuf:"varint,2,opt,name=dmg,proto3" json:"dmg,omitempty"`
	Hp    uint32 `protobuf:"varint,3,opt,name=hp,proto3" json:"hp,omitempty"`
	Spell uint32 `protobuf:"varint,4,opt,name=spell,proto3" json:"spell,omitempty"`
}

func (x *RecivedSpell) Reset() {
	*x = RecivedSpell{}
	if protoimpl.UnsafeEnabled {
		mi := &file_messages_proto_msgTypes[13]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *RecivedSpell) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RecivedSpell) ProtoMessage() {}

func (x *RecivedSpell) ProtoReflect() protoreflect.Message {
	mi := &file_messages_proto_msgTypes[13]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RecivedSpell.ProtoReflect.Descriptor instead.
func (*RecivedSpell) Descriptor() ([]byte, []int) {
	return file_messages_proto_rawDescGZIP(), []int{13}
}

func (x *RecivedSpell) GetId() uint32 {
	if x != nil {
		return x.Id
	}
	return 0
}

func (x *RecivedSpell) GetDmg() uint32 {
	if x != nil {
		return x.Dmg
	}
	return 0
}

func (x *RecivedSpell) GetHp() uint32 {
	if x != nil {
		return x.Hp
	}
	return 0
}

func (x *RecivedSpell) GetSpell() uint32 {
	if x != nil {
		return x.Spell
	}
	return 0
}

// Spell broadcast event,
// every player reciving this has the ids of the playes involved,
// so we just send this to reproduce the animations in their clients.
type SpellHit struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	From  uint32 `protobuf:"varint,2,opt,name=from,proto3" json:"from,omitempty"`
	To    uint32 `protobuf:"varint,3,opt,name=to,proto3" json:"to,omitempty"`
	Spell uint32 `protobuf:"varint,4,opt,name=spell,proto3" json:"spell,omitempty"`
}

func (x *SpellHit) Reset() {
	*x = SpellHit{}
	if protoimpl.UnsafeEnabled {
		mi := &file_messages_proto_msgTypes[14]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *SpellHit) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SpellHit) ProtoMessage() {}

func (x *SpellHit) ProtoReflect() protoreflect.Message {
	mi := &file_messages_proto_msgTypes[14]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SpellHit.ProtoReflect.Descriptor instead.
func (*SpellHit) Descriptor() ([]byte, []int) {
	return file_messages_proto_rawDescGZIP(), []int{14}
}

func (x *SpellHit) GetFrom() uint32 {
	if x != nil {
		return x.From
	}
	return 0
}

func (x *SpellHit) GetTo() uint32 {
	if x != nil {
		return x.To
	}
	return 0
}

func (x *SpellHit) GetSpell() uint32 {
	if x != nil {
		return x.Spell
	}
	return 0
}

// Potion asks to use a potion for mana or health points, specified in the `type`
type UsePotion struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Type uint32 `protobuf:"varint,1,opt,name=type,proto3" json:"type,omitempty"`
}

func (x *UsePotion) Reset() {
	*x = UsePotion{}
	if protoimpl.UnsafeEnabled {
		mi := &file_messages_proto_msgTypes[15]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *UsePotion) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UsePotion) ProtoMessage() {}

func (x *UsePotion) ProtoReflect() protoreflect.Message {
	mi := &file_messages_proto_msgTypes[15]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UsePotion.ProtoReflect.Descriptor instead.
func (*UsePotion) Descriptor() ([]byte, []int) {
	return file_messages_proto_rawDescGZIP(), []int{15}
}

func (x *UsePotion) GetType() uint32 {
	if x != nil {
		return x.Type
	}
	return 0
}

// PotionOk is the response for a potion use
type UsePotionOk struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Ok      bool   `protobuf:"varint,1,opt,name=ok,proto3" json:"ok,omitempty"`
	DeltaHP uint32 `protobuf:"varint,2,opt,name=deltaHP,proto3" json:"deltaHP,omitempty"`
	DeltaMP uint32 `protobuf:"varint,3,opt,name=deltaMP,proto3" json:"deltaMP,omitempty"`
}

func (x *UsePotionOk) Reset() {
	*x = UsePotionOk{}
	if protoimpl.UnsafeEnabled {
		mi := &file_messages_proto_msgTypes[16]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *UsePotionOk) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UsePotionOk) ProtoMessage() {}

func (x *UsePotionOk) ProtoReflect() protoreflect.Message {
	mi := &file_messages_proto_msgTypes[16]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UsePotionOk.ProtoReflect.Descriptor instead.
func (*UsePotionOk) Descriptor() ([]byte, []int) {
	return file_messages_proto_rawDescGZIP(), []int{16}
}

func (x *UsePotionOk) GetOk() bool {
	if x != nil {
		return x.Ok
	}
	return false
}

func (x *UsePotionOk) GetDeltaHP() uint32 {
	if x != nil {
		return x.DeltaHP
	}
	return 0
}

func (x *UsePotionOk) GetDeltaMP() uint32 {
	if x != nil {
		return x.DeltaMP
	}
	return 0
}

// PotionUsed is the event for the the client to reproduce the potion sound
// from the place it was sent, we dont need to know by who, just where
type PotionUsed struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	X uint32 `protobuf:"varint,1,opt,name=x,proto3" json:"x,omitempty"`
	Y uint32 `protobuf:"varint,2,opt,name=y,proto3" json:"y,omitempty"`
}

func (x *PotionUsed) Reset() {
	*x = PotionUsed{}
	if protoimpl.UnsafeEnabled {
		mi := &file_messages_proto_msgTypes[17]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *PotionUsed) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PotionUsed) ProtoMessage() {}

func (x *PotionUsed) ProtoReflect() protoreflect.Message {
	mi := &file_messages_proto_msgTypes[17]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PotionUsed.ProtoReflect.Descriptor instead.
func (*PotionUsed) Descriptor() ([]byte, []int) {
	return file_messages_proto_rawDescGZIP(), []int{17}
}

func (x *PotionUsed) GetX() uint32 {
	if x != nil {
		return x.X
	}
	return 0
}

func (x *PotionUsed) GetY() uint32 {
	if x != nil {
		return x.Y
	}
	return 0
}

// Player update
// The message the server sends all clients (*excluding the trigger client)
// about that players latest update.
// It should only be sent to players that are in range from this.
type PlayerAction struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Action uint32 `protobuf:"varint,1,opt,name=action,proto3" json:"action,omitempty"`
	Id     uint32 `protobuf:"varint,2,opt,name=id,proto3" json:"id,omitempty"`
	Nick   string `protobuf:"bytes,3,opt,name=nick,proto3" json:"nick,omitempty"`
	X      uint32 `protobuf:"varint,4,opt,name=x,proto3" json:"x,omitempty"`
	Y      uint32 `protobuf:"varint,5,opt,name=y,proto3" json:"y,omitempty"`
	D      uint32 `protobuf:"varint,6,opt,name=d,proto3" json:"d,omitempty"`
	Dead   bool   `protobuf:"varint,7,opt,name=dead,proto3" json:"dead,omitempty"`
	Armor  uint32 `protobuf:"varint,8,opt,name=armor,proto3" json:"armor,omitempty"`
	Helmet uint32 `protobuf:"varint,9,opt,name=helmet,proto3" json:"helmet,omitempty"`
	Weapon uint32 `protobuf:"varint,10,opt,name=weapon,proto3" json:"weapon,omitempty"`
	Shield uint32 `protobuf:"varint,11,opt,name=shield,proto3" json:"shield,omitempty"`
}

func (x *PlayerAction) Reset() {
	*x = PlayerAction{}
	if protoimpl.UnsafeEnabled {
		mi := &file_messages_proto_msgTypes[18]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *PlayerAction) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PlayerAction) ProtoMessage() {}

func (x *PlayerAction) ProtoReflect() protoreflect.Message {
	mi := &file_messages_proto_msgTypes[18]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PlayerAction.ProtoReflect.Descriptor instead.
func (*PlayerAction) Descriptor() ([]byte, []int) {
	return file_messages_proto_rawDescGZIP(), []int{18}
}

func (x *PlayerAction) GetAction() uint32 {
	if x != nil {
		return x.Action
	}
	return 0
}

func (x *PlayerAction) GetId() uint32 {
	if x != nil {
		return x.Id
	}
	return 0
}

func (x *PlayerAction) GetNick() string {
	if x != nil {
		return x.Nick
	}
	return ""
}

func (x *PlayerAction) GetX() uint32 {
	if x != nil {
		return x.X
	}
	return 0
}

func (x *PlayerAction) GetY() uint32 {
	if x != nil {
		return x.Y
	}
	return 0
}

func (x *PlayerAction) GetD() uint32 {
	if x != nil {
		return x.D
	}
	return 0
}

func (x *PlayerAction) GetDead() bool {
	if x != nil {
		return x.Dead
	}
	return false
}

func (x *PlayerAction) GetArmor() uint32 {
	if x != nil {
		return x.Armor
	}
	return 0
}

func (x *PlayerAction) GetHelmet() uint32 {
	if x != nil {
		return x.Helmet
	}
	return 0
}

func (x *PlayerAction) GetWeapon() uint32 {
	if x != nil {
		return x.Weapon
	}
	return 0
}

func (x *PlayerAction) GetShield() uint32 {
	if x != nil {
		return x.Shield
	}
	return 0
}

type PlayerActions struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	PlayerActions []*PlayerAction `protobuf:"bytes,1,rep,name=playerActions,proto3" json:"playerActions,omitempty"`
}

func (x *PlayerActions) Reset() {
	*x = PlayerActions{}
	if protoimpl.UnsafeEnabled {
		mi := &file_messages_proto_msgTypes[19]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *PlayerActions) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PlayerActions) ProtoMessage() {}

func (x *PlayerActions) ProtoReflect() protoreflect.Message {
	mi := &file_messages_proto_msgTypes[19]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PlayerActions.ProtoReflect.Descriptor instead.
func (*PlayerActions) Descriptor() ([]byte, []int) {
	return file_messages_proto_rawDescGZIP(), []int{19}
}

func (x *PlayerActions) GetPlayerActions() []*PlayerAction {
	if x != nil {
		return x.PlayerActions
	}
	return nil
}

// Spell cast
// Simple message the server sends all clients (*excluding the trigger client)
// when a spell is casted in the field of view of the player.
type SpellCast struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Type   uint32 `protobuf:"varint,1,opt,name=type,proto3" json:"type,omitempty"`
	Target uint32 `protobuf:"varint,4,opt,name=target,proto3" json:"target,omitempty"`
}

func (x *SpellCast) Reset() {
	*x = SpellCast{}
	if protoimpl.UnsafeEnabled {
		mi := &file_messages_proto_msgTypes[20]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *SpellCast) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SpellCast) ProtoMessage() {}

func (x *SpellCast) ProtoReflect() protoreflect.Message {
	mi := &file_messages_proto_msgTypes[20]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SpellCast.ProtoReflect.Descriptor instead.
func (*SpellCast) Descriptor() ([]byte, []int) {
	return file_messages_proto_rawDescGZIP(), []int{20}
}

func (x *SpellCast) GetType() uint32 {
	if x != nil {
		return x.Type
	}
	return 0
}

func (x *SpellCast) GetTarget() uint32 {
	if x != nil {
		return x.Target
	}
	return 0
}

var File_messages_proto protoreflect.FileDescriptor

var file_messages_proto_rawDesc = []byte{
	0x0a, 0x0e, 0x6d, 0x65, 0x73, 0x73, 0x61, 0x67, 0x65, 0x73, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f,
	0x12, 0x07, 0x6d, 0x65, 0x73, 0x73, 0x61, 0x67, 0x65, 0x22, 0x06, 0x0a, 0x04, 0x50, 0x69, 0x6e,
	0x67, 0x22, 0x39, 0x0a, 0x05, 0x45, 0x76, 0x65, 0x6e, 0x74, 0x12, 0x12, 0x0a, 0x04, 0x74, 0x79,
	0x70, 0x65, 0x18, 0x01, 0x20, 0x01, 0x28, 0x0d, 0x52, 0x04, 0x74, 0x79, 0x70, 0x65, 0x12, 0x0e,
	0x0a, 0x02, 0x69, 0x64, 0x18, 0x02, 0x20, 0x01, 0x28, 0x0d, 0x52, 0x02, 0x69, 0x64, 0x12, 0x0c,
	0x0a, 0x01, 0x65, 0x18, 0x03, 0x20, 0x01, 0x28, 0x0c, 0x52, 0x01, 0x65, 0x22, 0x1e, 0x0a, 0x08,
	0x52, 0x65, 0x67, 0x69, 0x73, 0x74, 0x65, 0x72, 0x12, 0x12, 0x0a, 0x04, 0x6e, 0x69, 0x63, 0x6b,
	0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x04, 0x6e, 0x69, 0x63, 0x6b, 0x22, 0xea, 0x01, 0x0a,
	0x0a, 0x52, 0x65, 0x67, 0x69, 0x73, 0x74, 0x65, 0x72, 0x4f, 0x6b, 0x12, 0x0e, 0x0a, 0x02, 0x69,
	0x64, 0x18, 0x01, 0x20, 0x01, 0x28, 0x0d, 0x52, 0x02, 0x69, 0x64, 0x12, 0x12, 0x0a, 0x04, 0x66,
	0x6f, 0x76, 0x58, 0x18, 0x04, 0x20, 0x01, 0x28, 0x05, 0x52, 0x04, 0x66, 0x6f, 0x76, 0x58, 0x12,
	0x12, 0x0a, 0x04, 0x66, 0x6f, 0x76, 0x59, 0x18, 0x05, 0x20, 0x01, 0x28, 0x05, 0x52, 0x04, 0x66,
	0x6f, 0x76, 0x59, 0x12, 0x29, 0x0a, 0x04, 0x73, 0x65, 0x6c, 0x66, 0x18, 0x06, 0x20, 0x01, 0x28,
	0x0b, 0x32, 0x15, 0x2e, 0x6d, 0x65, 0x73, 0x73, 0x61, 0x67, 0x65, 0x2e, 0x50, 0x6c, 0x61, 0x79,
	0x65, 0x72, 0x41, 0x63, 0x74, 0x69, 0x6f, 0x6e, 0x52, 0x04, 0x73, 0x65, 0x6c, 0x66, 0x12, 0x2d,
	0x0a, 0x06, 0x73, 0x70, 0x61, 0x77, 0x6e, 0x73, 0x18, 0x07, 0x20, 0x03, 0x28, 0x0b, 0x32, 0x15,
	0x2e, 0x6d, 0x65, 0x73, 0x73, 0x61, 0x67, 0x65, 0x2e, 0x50, 0x6c, 0x61, 0x79, 0x65, 0x72, 0x41,
	0x63, 0x74, 0x69, 0x6f, 0x6e, 0x52, 0x06, 0x73, 0x70, 0x61, 0x77, 0x6e, 0x73, 0x12, 0x14, 0x0a,
	0x05, 0x6d, 0x61, 0x78, 0x48, 0x50, 0x18, 0x08, 0x20, 0x01, 0x28, 0x0d, 0x52, 0x05, 0x6d, 0x61,
	0x78, 0x48, 0x50, 0x12, 0x14, 0x0a, 0x05, 0x6d, 0x61, 0x78, 0x4d, 0x50, 0x18, 0x09, 0x20, 0x01,
	0x28, 0x0d, 0x52, 0x05, 0x6d, 0x61, 0x78, 0x4d, 0x50, 0x12, 0x0e, 0x0a, 0x02, 0x48, 0x50, 0x18,
	0x0a, 0x20, 0x01, 0x28, 0x0d, 0x52, 0x02, 0x48, 0x50, 0x12, 0x0e, 0x0a, 0x02, 0x4d, 0x50, 0x18,
	0x0b, 0x20, 0x01, 0x28, 0x0d, 0x52, 0x02, 0x4d, 0x50, 0x22, 0x18, 0x0a, 0x04, 0x4d, 0x6f, 0x76,
	0x65, 0x12, 0x10, 0x0a, 0x03, 0x64, 0x69, 0x72, 0x18, 0x01, 0x20, 0x01, 0x28, 0x0d, 0x52, 0x03,
	0x64, 0x69, 0x72, 0x22, 0x18, 0x0a, 0x06, 0x4d, 0x6f, 0x76, 0x65, 0x4f, 0x6b, 0x12, 0x0e, 0x0a,
	0x02, 0x6f, 0x6b, 0x18, 0x01, 0x20, 0x01, 0x28, 0x08, 0x52, 0x02, 0x6f, 0x6b, 0x22, 0x17, 0x0a,
	0x03, 0x44, 0x69, 0x72, 0x12, 0x10, 0x0a, 0x03, 0x64, 0x69, 0x72, 0x18, 0x01, 0x20, 0x01, 0x28,
	0x0d, 0x52, 0x03, 0x64, 0x69, 0x72, 0x22, 0x0b, 0x0a, 0x09, 0x43, 0x61, 0x73, 0x74, 0x4d, 0x65,
	0x6c, 0x65, 0x65, 0x22, 0x3f, 0x0a, 0x0b, 0x43, 0x61, 0x73, 0x74, 0x4d, 0x65, 0x6c, 0x65, 0x65,
	0x4f, 0x6b, 0x12, 0x0e, 0x0a, 0x02, 0x6f, 0x6b, 0x18, 0x01, 0x20, 0x01, 0x28, 0x08, 0x52, 0x02,
	0x6f, 0x6b, 0x12, 0x0e, 0x0a, 0x02, 0x69, 0x64, 0x18, 0x02, 0x20, 0x01, 0x28, 0x0d, 0x52, 0x02,
	0x69, 0x64, 0x12, 0x10, 0x0a, 0x03, 0x64, 0x6d, 0x67, 0x18, 0x03, 0x20, 0x01, 0x28, 0x0d, 0x52,
	0x03, 0x64, 0x6d, 0x67, 0x22, 0x40, 0x0a, 0x0c, 0x52, 0x65, 0x63, 0x69, 0x76, 0x65, 0x64, 0x4d,
	0x65, 0x6c, 0x65, 0x65, 0x12, 0x0e, 0x0a, 0x02, 0x69, 0x64, 0x18, 0x01, 0x20, 0x01, 0x28, 0x0d,
	0x52, 0x02, 0x69, 0x64, 0x12, 0x10, 0x0a, 0x03, 0x64, 0x6d, 0x67, 0x18, 0x02, 0x20, 0x01, 0x28,
	0x0d, 0x52, 0x03, 0x64, 0x6d, 0x67, 0x12, 0x0e, 0x0a, 0x02, 0x68, 0x70, 0x18, 0x03, 0x20, 0x01,
	0x28, 0x0d, 0x52, 0x02, 0x68, 0x70, 0x22, 0x3e, 0x0a, 0x08, 0x4d, 0x65, 0x6c, 0x65, 0x65, 0x48,
	0x69, 0x74, 0x12, 0x0e, 0x0a, 0x02, 0x6f, 0x6b, 0x18, 0x01, 0x20, 0x01, 0x28, 0x08, 0x52, 0x02,
	0x6f, 0x6b, 0x12, 0x12, 0x0a, 0x04, 0x66, 0x72, 0x6f, 0x6d, 0x18, 0x02, 0x20, 0x01, 0x28, 0x0d,
	0x52, 0x04, 0x66, 0x72, 0x6f, 0x6d, 0x12, 0x0e, 0x0a, 0x02, 0x74, 0x6f, 0x18, 0x03, 0x20, 0x01,
	0x28, 0x0d, 0x52, 0x02, 0x74, 0x6f, 0x22, 0x3d, 0x0a, 0x09, 0x43, 0x61, 0x73, 0x74, 0x53, 0x70,
	0x65, 0x6c, 0x6c, 0x12, 0x0c, 0x0a, 0x01, 0x78, 0x18, 0x01, 0x20, 0x01, 0x28, 0x0d, 0x52, 0x01,
	0x78, 0x12, 0x0c, 0x0a, 0x01, 0x79, 0x18, 0x02, 0x20, 0x01, 0x28, 0x0d, 0x52, 0x01, 0x79, 0x12,
	0x14, 0x0a, 0x05, 0x73, 0x70, 0x65, 0x6c, 0x6c, 0x18, 0x03, 0x20, 0x01, 0x28, 0x0d, 0x52, 0x05,
	0x73, 0x70, 0x65, 0x6c, 0x6c, 0x22, 0x65, 0x0a, 0x0b, 0x43, 0x61, 0x73, 0x74, 0x53, 0x70, 0x65,
	0x6c, 0x6c, 0x4f, 0x6b, 0x12, 0x0e, 0x0a, 0x02, 0x6f, 0x6b, 0x18, 0x01, 0x20, 0x01, 0x28, 0x08,
	0x52, 0x02, 0x6f, 0x6b, 0x12, 0x0e, 0x0a, 0x02, 0x69, 0x64, 0x18, 0x02, 0x20, 0x01, 0x28, 0x0d,
	0x52, 0x02, 0x69, 0x64, 0x12, 0x10, 0x0a, 0x03, 0x64, 0x6d, 0x67, 0x18, 0x03, 0x20, 0x01, 0x28,
	0x0d, 0x52, 0x03, 0x64, 0x6d, 0x67, 0x12, 0x14, 0x0a, 0x05, 0x73, 0x70, 0x65, 0x6c, 0x6c, 0x18,
	0x04, 0x20, 0x01, 0x28, 0x0d, 0x52, 0x05, 0x73, 0x70, 0x65, 0x6c, 0x6c, 0x12, 0x0e, 0x0a, 0x02,
	0x6d, 0x70, 0x18, 0x05, 0x20, 0x01, 0x28, 0x0d, 0x52, 0x02, 0x6d, 0x70, 0x22, 0x56, 0x0a, 0x0c,
	0x52, 0x65, 0x63, 0x69, 0x76, 0x65, 0x64, 0x53, 0x70, 0x65, 0x6c, 0x6c, 0x12, 0x0e, 0x0a, 0x02,
	0x69, 0x64, 0x18, 0x01, 0x20, 0x01, 0x28, 0x0d, 0x52, 0x02, 0x69, 0x64, 0x12, 0x10, 0x0a, 0x03,
	0x64, 0x6d, 0x67, 0x18, 0x02, 0x20, 0x01, 0x28, 0x0d, 0x52, 0x03, 0x64, 0x6d, 0x67, 0x12, 0x0e,
	0x0a, 0x02, 0x68, 0x70, 0x18, 0x03, 0x20, 0x01, 0x28, 0x0d, 0x52, 0x02, 0x68, 0x70, 0x12, 0x14,
	0x0a, 0x05, 0x73, 0x70, 0x65, 0x6c, 0x6c, 0x18, 0x04, 0x20, 0x01, 0x28, 0x0d, 0x52, 0x05, 0x73,
	0x70, 0x65, 0x6c, 0x6c, 0x22, 0x44, 0x0a, 0x08, 0x53, 0x70, 0x65, 0x6c, 0x6c, 0x48, 0x69, 0x74,
	0x12, 0x12, 0x0a, 0x04, 0x66, 0x72, 0x6f, 0x6d, 0x18, 0x02, 0x20, 0x01, 0x28, 0x0d, 0x52, 0x04,
	0x66, 0x72, 0x6f, 0x6d, 0x12, 0x0e, 0x0a, 0x02, 0x74, 0x6f, 0x18, 0x03, 0x20, 0x01, 0x28, 0x0d,
	0x52, 0x02, 0x74, 0x6f, 0x12, 0x14, 0x0a, 0x05, 0x73, 0x70, 0x65, 0x6c, 0x6c, 0x18, 0x04, 0x20,
	0x01, 0x28, 0x0d, 0x52, 0x05, 0x73, 0x70, 0x65, 0x6c, 0x6c, 0x22, 0x1f, 0x0a, 0x09, 0x55, 0x73,
	0x65, 0x50, 0x6f, 0x74, 0x69, 0x6f, 0x6e, 0x12, 0x12, 0x0a, 0x04, 0x74, 0x79, 0x70, 0x65, 0x18,
	0x01, 0x20, 0x01, 0x28, 0x0d, 0x52, 0x04, 0x74, 0x79, 0x70, 0x65, 0x22, 0x51, 0x0a, 0x0b, 0x55,
	0x73, 0x65, 0x50, 0x6f, 0x74, 0x69, 0x6f, 0x6e, 0x4f, 0x6b, 0x12, 0x0e, 0x0a, 0x02, 0x6f, 0x6b,
	0x18, 0x01, 0x20, 0x01, 0x28, 0x08, 0x52, 0x02, 0x6f, 0x6b, 0x12, 0x18, 0x0a, 0x07, 0x64, 0x65,
	0x6c, 0x74, 0x61, 0x48, 0x50, 0x18, 0x02, 0x20, 0x01, 0x28, 0x0d, 0x52, 0x07, 0x64, 0x65, 0x6c,
	0x74, 0x61, 0x48, 0x50, 0x12, 0x18, 0x0a, 0x07, 0x64, 0x65, 0x6c, 0x74, 0x61, 0x4d, 0x50, 0x18,
	0x03, 0x20, 0x01, 0x28, 0x0d, 0x52, 0x07, 0x64, 0x65, 0x6c, 0x74, 0x61, 0x4d, 0x50, 0x22, 0x28,
	0x0a, 0x0a, 0x50, 0x6f, 0x74, 0x69, 0x6f, 0x6e, 0x55, 0x73, 0x65, 0x64, 0x12, 0x0c, 0x0a, 0x01,
	0x78, 0x18, 0x01, 0x20, 0x01, 0x28, 0x0d, 0x52, 0x01, 0x78, 0x12, 0x0c, 0x0a, 0x01, 0x79, 0x18,
	0x02, 0x20, 0x01, 0x28, 0x0d, 0x52, 0x01, 0x79, 0x22, 0xe6, 0x01, 0x0a, 0x0c, 0x50, 0x6c, 0x61,
	0x79, 0x65, 0x72, 0x41, 0x63, 0x74, 0x69, 0x6f, 0x6e, 0x12, 0x16, 0x0a, 0x06, 0x61, 0x63, 0x74,
	0x69, 0x6f, 0x6e, 0x18, 0x01, 0x20, 0x01, 0x28, 0x0d, 0x52, 0x06, 0x61, 0x63, 0x74, 0x69, 0x6f,
	0x6e, 0x12, 0x0e, 0x0a, 0x02, 0x69, 0x64, 0x18, 0x02, 0x20, 0x01, 0x28, 0x0d, 0x52, 0x02, 0x69,
	0x64, 0x12, 0x12, 0x0a, 0x04, 0x6e, 0x69, 0x63, 0x6b, 0x18, 0x03, 0x20, 0x01, 0x28, 0x09, 0x52,
	0x04, 0x6e, 0x69, 0x63, 0x6b, 0x12, 0x0c, 0x0a, 0x01, 0x78, 0x18, 0x04, 0x20, 0x01, 0x28, 0x0d,
	0x52, 0x01, 0x78, 0x12, 0x0c, 0x0a, 0x01, 0x79, 0x18, 0x05, 0x20, 0x01, 0x28, 0x0d, 0x52, 0x01,
	0x79, 0x12, 0x0c, 0x0a, 0x01, 0x64, 0x18, 0x06, 0x20, 0x01, 0x28, 0x0d, 0x52, 0x01, 0x64, 0x12,
	0x12, 0x0a, 0x04, 0x64, 0x65, 0x61, 0x64, 0x18, 0x07, 0x20, 0x01, 0x28, 0x08, 0x52, 0x04, 0x64,
	0x65, 0x61, 0x64, 0x12, 0x14, 0x0a, 0x05, 0x61, 0x72, 0x6d, 0x6f, 0x72, 0x18, 0x08, 0x20, 0x01,
	0x28, 0x0d, 0x52, 0x05, 0x61, 0x72, 0x6d, 0x6f, 0x72, 0x12, 0x16, 0x0a, 0x06, 0x68, 0x65, 0x6c,
	0x6d, 0x65, 0x74, 0x18, 0x09, 0x20, 0x01, 0x28, 0x0d, 0x52, 0x06, 0x68, 0x65, 0x6c, 0x6d, 0x65,
	0x74, 0x12, 0x16, 0x0a, 0x06, 0x77, 0x65, 0x61, 0x70, 0x6f, 0x6e, 0x18, 0x0a, 0x20, 0x01, 0x28,
	0x0d, 0x52, 0x06, 0x77, 0x65, 0x61, 0x70, 0x6f, 0x6e, 0x12, 0x16, 0x0a, 0x06, 0x73, 0x68, 0x69,
	0x65, 0x6c, 0x64, 0x18, 0x0b, 0x20, 0x01, 0x28, 0x0d, 0x52, 0x06, 0x73, 0x68, 0x69, 0x65, 0x6c,
	0x64, 0x22, 0x4c, 0x0a, 0x0d, 0x50, 0x6c, 0x61, 0x79, 0x65, 0x72, 0x41, 0x63, 0x74, 0x69, 0x6f,
	0x6e, 0x73, 0x12, 0x3b, 0x0a, 0x0d, 0x70, 0x6c, 0x61, 0x79, 0x65, 0x72, 0x41, 0x63, 0x74, 0x69,
	0x6f, 0x6e, 0x73, 0x18, 0x01, 0x20, 0x03, 0x28, 0x0b, 0x32, 0x15, 0x2e, 0x6d, 0x65, 0x73, 0x73,
	0x61, 0x67, 0x65, 0x2e, 0x50, 0x6c, 0x61, 0x79, 0x65, 0x72, 0x41, 0x63, 0x74, 0x69, 0x6f, 0x6e,
	0x52, 0x0d, 0x70, 0x6c, 0x61, 0x79, 0x65, 0x72, 0x41, 0x63, 0x74, 0x69, 0x6f, 0x6e, 0x73, 0x22,
	0x37, 0x0a, 0x09, 0x53, 0x70, 0x65, 0x6c, 0x6c, 0x43, 0x61, 0x73, 0x74, 0x12, 0x12, 0x0a, 0x04,
	0x74, 0x79, 0x70, 0x65, 0x18, 0x01, 0x20, 0x01, 0x28, 0x0d, 0x52, 0x04, 0x74, 0x79, 0x70, 0x65,
	0x12, 0x16, 0x0a, 0x06, 0x74, 0x61, 0x72, 0x67, 0x65, 0x74, 0x18, 0x04, 0x20, 0x01, 0x28, 0x0d,
	0x52, 0x06, 0x74, 0x61, 0x72, 0x67, 0x65, 0x74, 0x42, 0x0a, 0x5a, 0x08, 0x2f, 0x6d, 0x65, 0x73,
	0x73, 0x61, 0x67, 0x65, 0x62, 0x06, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x33,
}

var (
	file_messages_proto_rawDescOnce sync.Once
	file_messages_proto_rawDescData = file_messages_proto_rawDesc
)

func file_messages_proto_rawDescGZIP() []byte {
	file_messages_proto_rawDescOnce.Do(func() {
		file_messages_proto_rawDescData = protoimpl.X.CompressGZIP(file_messages_proto_rawDescData)
	})
	return file_messages_proto_rawDescData
}

var file_messages_proto_msgTypes = make([]protoimpl.MessageInfo, 21)
var file_messages_proto_goTypes = []interface{}{
	(*Ping)(nil),          // 0: message.Ping
	(*Event)(nil),         // 1: message.Event
	(*Register)(nil),      // 2: message.Register
	(*RegisterOk)(nil),    // 3: message.RegisterOk
	(*Move)(nil),          // 4: message.Move
	(*MoveOk)(nil),        // 5: message.MoveOk
	(*Dir)(nil),           // 6: message.Dir
	(*CastMelee)(nil),     // 7: message.CastMelee
	(*CastMeleeOk)(nil),   // 8: message.CastMeleeOk
	(*RecivedMelee)(nil),  // 9: message.RecivedMelee
	(*MeleeHit)(nil),      // 10: message.MeleeHit
	(*CastSpell)(nil),     // 11: message.CastSpell
	(*CastSpellOk)(nil),   // 12: message.CastSpellOk
	(*RecivedSpell)(nil),  // 13: message.RecivedSpell
	(*SpellHit)(nil),      // 14: message.SpellHit
	(*UsePotion)(nil),     // 15: message.UsePotion
	(*UsePotionOk)(nil),   // 16: message.UsePotionOk
	(*PotionUsed)(nil),    // 17: message.PotionUsed
	(*PlayerAction)(nil),  // 18: message.PlayerAction
	(*PlayerActions)(nil), // 19: message.PlayerActions
	(*SpellCast)(nil),     // 20: message.SpellCast
}
var file_messages_proto_depIdxs = []int32{
	18, // 0: message.RegisterOk.self:type_name -> message.PlayerAction
	18, // 1: message.RegisterOk.spawns:type_name -> message.PlayerAction
	18, // 2: message.PlayerActions.playerActions:type_name -> message.PlayerAction
	3,  // [3:3] is the sub-list for method output_type
	3,  // [3:3] is the sub-list for method input_type
	3,  // [3:3] is the sub-list for extension type_name
	3,  // [3:3] is the sub-list for extension extendee
	0,  // [0:3] is the sub-list for field type_name
}

func init() { file_messages_proto_init() }
func file_messages_proto_init() {
	if File_messages_proto != nil {
		return
	}
	if !protoimpl.UnsafeEnabled {
		file_messages_proto_msgTypes[0].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*Ping); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_messages_proto_msgTypes[1].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*Event); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_messages_proto_msgTypes[2].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*Register); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_messages_proto_msgTypes[3].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*RegisterOk); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_messages_proto_msgTypes[4].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*Move); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_messages_proto_msgTypes[5].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*MoveOk); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_messages_proto_msgTypes[6].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*Dir); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_messages_proto_msgTypes[7].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*CastMelee); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_messages_proto_msgTypes[8].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*CastMeleeOk); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_messages_proto_msgTypes[9].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*RecivedMelee); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_messages_proto_msgTypes[10].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*MeleeHit); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_messages_proto_msgTypes[11].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*CastSpell); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_messages_proto_msgTypes[12].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*CastSpellOk); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_messages_proto_msgTypes[13].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*RecivedSpell); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_messages_proto_msgTypes[14].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*SpellHit); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_messages_proto_msgTypes[15].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*UsePotion); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_messages_proto_msgTypes[16].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*UsePotionOk); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_messages_proto_msgTypes[17].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*PotionUsed); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_messages_proto_msgTypes[18].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*PlayerAction); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_messages_proto_msgTypes[19].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*PlayerActions); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_messages_proto_msgTypes[20].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*SpellCast); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_messages_proto_rawDesc,
			NumEnums:      0,
			NumMessages:   21,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_messages_proto_goTypes,
		DependencyIndexes: file_messages_proto_depIdxs,
		MessageInfos:      file_messages_proto_msgTypes,
	}.Build()
	File_messages_proto = out.File
	file_messages_proto_rawDesc = nil
	file_messages_proto_goTypes = nil
	file_messages_proto_depIdxs = nil
}
